"use client";
import { useEffect, useState } from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";
const FRONTEND_VERSION="0.47.5";
export default function FreshDataButton(){
  const [status,setStatus]=useState(null),[health,setHealth]=useState(null),[diagnostics,setDiagnostics]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function load(){setMessage("");try{const hr=await fetch(`${API}/health`,{cache:"no-store"});if(!hr.ok)throw new Error(`Backend svarar med ${hr.status}`);const h=await hr.json();setHealth(h);if(h.version!==FRONTEND_VERSION){setMessage(`VERSIONERNA MATCHAR INTE: frontend v${FRONTEND_VERSION}, backend v${h.version}. Starta om backend från v${FRONTEND_VERSION}.`);setStatus(null);setDiagnostics(null);return;}const [sr,dr]=await Promise.all([fetch(`${API}/admin/update-manager/status`,{cache:"no-store"}),fetch(`${API}/system/diagnostics`,{cache:"no-store"})]);if(!sr.ok)throw new Error(`Update Manager saknas (${sr.status}). Starta om backend.`);setStatus(await sr.json());if(dr.ok)setDiagnostics(await dr.json());}catch(e){setMessage(`BACKENDPROBLEM: ${e.message||"kunde inte nå backend"}`)}}
  useEffect(()=>{load()},[]);
  async function repairIfNeeded(){const dr=await fetch(`${API}/system/diagnostics`,{cache:"no-store"});if(!dr.ok)throw new Error("Diagnostik saknas. Starta om backend med v0.46.1.");const d=await dr.json();setDiagnostics(d);if(d.status==="needs_repair"){const rr=await fetch(`${API}/system/repair`,{method:"POST"});if(!rr.ok)throw new Error("Databasen kunde inte repareras.");const repaired=await rr.json();setDiagnostics({...d,status:"ok",counts:repaired.counts,problems:[]});return repaired;}return null;}
  async function run(){setBusy(true);setMessage("");try{const hr=await fetch(`${API}/health`,{cache:"no-store"});if(!hr.ok)throw new Error("Backend svarar inte korrekt.");const h=await hr.json();setHealth(h);if(h.version!==FRONTEND_VERSION)throw new Error(`Frontend är v${FRONTEND_VERSION} men backend är v${h.version}. Starta om backend först.`);const repaired=await repairIfNeeded();const r=await fetch(`${API}/admin/update-manager/run`,{method:"POST"});const data=await r.json();if(!r.ok)throw new Error(data.detail||`Update Manager svarade ${r.status}.`);const checked=data.checked??0,success=data.success??0,blocked=data.blocked??0,fetched=data.fetched??0;const repairText=repaired?.starter_catalog_ready?" Testkatalogen reparerades också.":"";setMessage(`Klart: ${checked} källor kontrollerade · ${success} lyckades · ${blocked} blockerade · ${fetched} poster hämtade.${repairText}`);await load();setTimeout(()=>location.reload(),1100);}catch(e){setMessage(e.message||"Uppdateringen misslyckades.");}finally{setBusy(false);}}
  const mismatch=health?.version&&health.version!==FRONTEND_VERSION;const last=status?.last_run_finished_at?new Date(status.last_run_finished_at).toLocaleString("sv-SE"):"Inte körd ännu";const starter=diagnostics?.counts?.starter_products;
  return <div className={`freshDataBox ${mismatch?"freshDataError":""}`}><div><small>DATASTATUS</small><b>{mismatch?`Backend v${health.version} · Frontend v${FRONTEND_VERSION}`:`Senast uppdaterad: ${last}`}</b><span>{mismatch?"Backend måste startas om innan appen kan använda den nya datamotorn.":`Automatisk kontroll var 6:e timme.${starter!=null?` Testkatalog: ${starter}/3 produkter.`:""} Manuella körningar respekterar alltid källornas policyspärrar.`}</span></div><button onClick={run} disabled={busy||status?.running||mismatch}>{busy||status?.running?"UPPDATERAR…":mismatch?"STARTA OM BACKEND":"↻ UPPDATERA + KONTROLLERA DATA"}</button>{message&&<p>{message}</p>}</div>
}
